root = "."
tmp_dir = "tmp"

[build]
cmd = "make build"
bin = "build/web"
full_bin = "GO111MODULE=on ./build/web"
include_ext = ["go"]
exclude_dir = ["misc", "build", "tmp"]

stop_on_error = true

delay = 1000
kill_delay = 10

log = "air_errors.log"

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
