with-expecter: false
filename: "{{.InterfaceNameSnake}}_mock.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
all: True
recursive: True
packages:
  loan-service/models:
    config:
      all: True
  loan-service/services:
    config:
      all: True
