version: "3"
services:
  web:
    image: golang:1.20.4-alpine3.17
    container_name: loan-service-web
    build:
      context: .
      dockerfile: ${DOCKERFILE_PATH}
    restart: always
    ports:
      - "8080:8080"
      - "4080:4080" # dlv debugger
    depends_on:
      postgres:
        condition: service_started
    env_file:
      - .env
    volumes:
      - ./:/app
  postgres:
    image: postgres:13-alpine
    container_name: loan-service-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5555:5432"
    volumes:
      - "/tmp/postgres/data:/var/lib/postgresql/data"
